"""Add_user_id_to_reports

Revision ID: 213aee94c5b0
Revises: 5fd0e59ee50f
Create Date: 2025-12-23 22:29:06.007606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from models import User  # Import User model to query id

# revision identifiers, used by Alembic.
revision: str = '213aee94c5b0'
down_revision: Union[str, None] = '5fd0e59ee50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('is_uploaded', sa.Boolean(), nullable=True))
    
    # Data backfill step
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # Find user 'yjia0405@gmail.com'
    # Note: Using raw SQL to be safe against model changes, or careful model import
    try:
        result = session.execute(sa.text("SELECT id FROM users WHERE username = 'yjia0405@gmail.com'"))
        user_row = result.first()
        
        if user_row:
            user_id = user_row[0]
            print(f"Found user yjia0405@gmail.com with ID: {user_id}. Backfilling reports...")
            
            # Execute updates
            op.execute(
                sa.text(f"UPDATE reports SET user_id = {user_id} WHERE user_id IS NULL")
            )
            
            # Set default is_uploaded to False (0 in sqlite)
            op.execute(
                sa.text("UPDATE reports SET is_uploaded = 0 WHERE is_uploaded IS NULL")
            )
        else:
            print("Warning: User 'yjia0405@gmail.com' not found. Existing reports will have user_id=NULL.")
            
    except Exception as e:
        print(f"Error during data backfill: {e}")
    finally:
        session.close()

    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    
    # Fix for SQLite foreign key creation:
    # SQLite requires recreating the table to add a foreign key constraint properly if not using batch.
    # But for a simple column add + FK, batch operates well.
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_reports_user_id', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_user_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_reports_user_id'))
        batch_op.drop_column('is_uploaded')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
