"""add_target_total_stocks

Revision ID: 5135e29cfa34
Revises: deebfac90985
Create Date: 2026-02-21 17:48:07.442145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5135e29cfa34'
down_revision: Union[str, None] = 'deebfac90985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_runs', sa.Column('target_total_stocks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_runs', 'target_total_stocks')
    # ### end Alembic commands ###
