"""Initial_migration

Revision ID: 5fd0e59ee50f
Revises: 
Create Date: 2025-12-23 22:25:38.357423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '5fd0e59ee50f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get database connection
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    # Create system_config only if it doesn't exist
    if 'system_config' not in tables:
        op.create_table('system_config',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('key')
        )
        op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=False)
    
    # Drop tables/indexes if they exist (handling potential errors if they don't)
    try:
        op.drop_index('ix_events_id', table_name='events')
        op.drop_index('ix_events_ticker', table_name='events')
        op.drop_index('ix_events_user_id', table_name='events')
        op.drop_table('events')
    except Exception:
        pass

    try:
        op.drop_index('ix_user_alert_preferences_id', table_name='user_alert_preferences')
        op.drop_index('ix_user_alert_preferences_user_id', table_name='user_alert_preferences')
        op.drop_table('user_alert_preferences')
    except Exception:
        pass

    # Batch alter for filing_13f
    with op.batch_alter_table('filing_13f', schema=None) as batch_op:
        batch_op.alter_column('total_value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # Batch alter for position_changes
    with op.batch_alter_table('position_changes', schema=None) as batch_op:
        batch_op.alter_column('institution_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('current_shares',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('prior_shares',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('shares_change',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('current_value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('prior_value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('is_whale',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        # Drop indexes only if present? Batch usually handles this gracefully but safe to wrap or just let it try
        try:
            batch_op.drop_index('ix_position_changes_change_type')
        except: pass
        try:
            batch_op.drop_index('ix_position_changes_current_quarter')
        except: pass
        try:
            batch_op.drop_index('ix_position_changes_is_whale')
        except: pass

    # Batch alter for whale_alerts
    with op.batch_alter_table('whale_alerts', schema=None) as batch_op:
        batch_op.alter_column('shares_change',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('value_change',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        try:
            batch_op.drop_index('ix_whale_alerts_cik')
        except: pass
        try:
            batch_op.drop_index('ix_whale_alerts_created_at')
        except: pass
        try:
            batch_op.drop_index('ix_whale_alerts_quarter')
        except: pass
        
        # Foreign keys are tricky in SQLite batch mode, often require recreation. 
        # But drop_constraint might fail silently or work if named properly.
        # Assuming we just want to proceed with column changes mainly.
        # try:
        #     batch_op.drop_constraint(None, type_='foreignkey')
        # except: pass
        pass
        
        try:
            batch_op.drop_column('cik')
        except: pass
        try:
            batch_op.drop_column('position_change_id')
        except: pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
