"""Add stripe and verification fields to user

Revision ID: c88915016c31
Revises: 
Create Date: 2025-12-30 05:01:22.465608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c88915016c31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alphatrade_watchlist_id', table_name='alphatrade_watchlist')
    op.drop_index('ix_alphatrade_watchlist_ticker', table_name='alphatrade_watchlist')
    op.drop_index('ix_alphatrade_watchlist_user_id', table_name='alphatrade_watchlist')
    op.drop_table('alphatrade_watchlist')
    op.drop_index('ix_user_alert_preferences_id', table_name='user_alert_preferences')
    op.drop_index('ix_user_alert_preferences_user_id', table_name='user_alert_preferences')
    op.drop_table('user_alert_preferences')
    op.drop_column('alphatrade_positions', 'current_price')
    op.alter_column('position_changes', 'institution_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('position_changes', 'current_shares',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('position_changes', 'prior_shares',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('position_changes', 'shares_change',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('position_changes', 'current_value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('position_changes', 'prior_value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('position_changes', 'is_whale',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_position_changes_change_type', table_name='position_changes')
    op.drop_index('ix_position_changes_current_quarter', table_name='position_changes')
    op.drop_index('ix_position_changes_is_whale', table_name='position_changes')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_users_role', table_name='users')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.alter_column('whale_alerts', 'shares_change',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('whale_alerts', 'value_change',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('whale_alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_whale_alerts_cik', table_name='whale_alerts')
    op.drop_index('ix_whale_alerts_created_at', table_name='whale_alerts')
    op.drop_index('ix_whale_alerts_quarter', table_name='whale_alerts')
    op.drop_constraint('whale_alerts_position_change_id_fkey', 'whale_alerts', type_='foreignkey')
    op.drop_column('whale_alerts', 'position_change_id')
    op.drop_column('whale_alerts', 'cik')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whale_alerts', sa.Column('cik', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('whale_alerts', sa.Column('position_change_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('whale_alerts_position_change_id_fkey', 'whale_alerts', 'position_changes', ['position_change_id'], ['id'])
    op.create_index('ix_whale_alerts_quarter', 'whale_alerts', ['quarter'], unique=False)
    op.create_index('ix_whale_alerts_created_at', 'whale_alerts', ['created_at'], unique=False)
    op.create_index('ix_whale_alerts_cik', 'whale_alerts', ['cik'], unique=False)
    op.alter_column('whale_alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('whale_alerts', 'value_change',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('whale_alerts', 'shares_change',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.drop_column('users', 'stripe_current_period_end')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_index('ix_position_changes_is_whale', 'position_changes', ['is_whale'], unique=False)
    op.create_index('ix_position_changes_current_quarter', 'position_changes', ['current_quarter'], unique=False)
    op.create_index('ix_position_changes_change_type', 'position_changes', ['change_type'], unique=False)
    op.alter_column('position_changes', 'is_whale',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('position_changes', 'prior_value',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('position_changes', 'current_value',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('position_changes', 'shares_change',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('position_changes', 'prior_shares',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('position_changes', 'current_shares',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('position_changes', 'institution_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('alphatrade_positions', sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_table('user_alert_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('watch_tickers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('watch_institutions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_position_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_percent_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('alert_on_new_positions', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_on_exits', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_on_increases', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('alert_on_decreases', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_alert_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_alert_preferences_pkey')
    )
    op.create_index('ix_user_alert_preferences_user_id', 'user_alert_preferences', ['user_id'], unique=False)
    op.create_index('ix_user_alert_preferences_id', 'user_alert_preferences', ['id'], unique=False)
    op.create_table('alphatrade_watchlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='alphatrade_watchlist_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alphatrade_watchlist_pkey'),
    sa.UniqueConstraint('user_id', 'ticker', name='uix_watchlist_user_ticker')
    )
    op.create_index('ix_alphatrade_watchlist_user_id', 'alphatrade_watchlist', ['user_id'], unique=False)
    op.create_index('ix_alphatrade_watchlist_ticker', 'alphatrade_watchlist', ['ticker'], unique=False)
    op.create_index('ix_alphatrade_watchlist_id', 'alphatrade_watchlist', ['id'], unique=False)
    # ### end Alembic commands ###
