"""Add stock screener models

Revision ID: deebfac90985
Revises: d9360293cda9
Create Date: 2026-02-14 14:08:05.098834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deebfac90985'
down_revision: Union[str, None] = 'd9360293cda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statement_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'statement_type', 'fiscal_year', 'period', name='uix_ticker_statement_year')
    )
    op.create_index(op.f('ix_financial_statement_cache_id'), 'financial_statement_cache', ['id'], unique=False)
    op.create_index(op.f('ix_financial_statement_cache_ticker'), 'financial_statement_cache', ['ticker'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('can_access', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'resource', name='uix_role_resource')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_resource'), 'role_permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('screening_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_stocks_processed', sa.Integer(), nullable=True),
    sa.Column('total_flagged', sa.Integer(), nullable=True),
    sa.Column('strategies_run', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_runs_id'), 'screening_runs', ['id'], unique=False)
    op.create_index(op.f('ix_screening_runs_run_date'), 'screening_runs', ['run_date'], unique=False)
    op.create_table('stock_universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_universe_id'), 'stock_universe', ['id'], unique=False)
    op.create_index(op.f('ix_stock_universe_ticker'), 'stock_universe', ['ticker'], unique=True)
    op.create_table('flagged_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('screening_run_id', sa.Integer(), nullable=True),
    sa.Column('screening_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('strategies_flagged', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('financial_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'screening_date', name='uix_ticker_screening_date')
    )
    op.create_index(op.f('ix_flagged_companies_id'), 'flagged_companies', ['id'], unique=False)
    op.create_index(op.f('ix_flagged_companies_screening_date'), 'flagged_companies', ['screening_date'], unique=False)
    op.create_index(op.f('ix_flagged_companies_screening_run_id'), 'flagged_companies', ['screening_run_id'], unique=False)
    op.create_index(op.f('ix_flagged_companies_ticker'), 'flagged_companies', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flagged_companies_ticker'), table_name='flagged_companies')
    op.drop_index(op.f('ix_flagged_companies_screening_run_id'), table_name='flagged_companies')
    op.drop_index(op.f('ix_flagged_companies_screening_date'), table_name='flagged_companies')
    op.drop_index(op.f('ix_flagged_companies_id'), table_name='flagged_companies')
    op.drop_table('flagged_companies')
    op.drop_index(op.f('ix_stock_universe_ticker'), table_name='stock_universe')
    op.drop_index(op.f('ix_stock_universe_id'), table_name='stock_universe')
    op.drop_table('stock_universe')
    op.drop_index(op.f('ix_screening_runs_run_date'), table_name='screening_runs')
    op.drop_index(op.f('ix_screening_runs_id'), table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_resource'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_financial_statement_cache_ticker'), table_name='financial_statement_cache')
    op.drop_index(op.f('ix_financial_statement_cache_id'), table_name='financial_statement_cache')
    op.drop_table('financial_statement_cache')
    # ### end Alembic commands ###
